# Generated by Django 2.0.5 on 2018-05-29 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('padid', models.CharField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('template_is_public', models.BooleanField(default=False)),
                ('template_password', models.CharField(blank=True, max_length=256)),
                ('template_padname', models.CharField(blank=True, max_length=256)),
                ('template_slug', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PadAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorID', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='PadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padman.PadCategory')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='PadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_mapper', models.SlugField(max_length=256, unique=True)),
                ('groupID', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padman.PadCategory')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='PadServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(help_text='must have trailing /', max_length=256, verbose_name='URL')),
                ('apikey', models.CharField(max_length=256, verbose_name='API key')),
                ('notes', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
            },
        ),
        migrations.AddField(
            model_name='padgroup',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padman.PadServer'),
        ),
        migrations.AddField(
            model_name='padauthor',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padman.PadServer'),
        ),
        migrations.AddField(
            model_name='padauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pad',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='padman.PadGroup'),
        ),
        migrations.AddField(
            model_name='pad',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padman.PadServer'),
        ),
    ]
