# Generated by Django 2.0.5 on 2018-05-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='padserver',
            name='backend',
            field=models.CharField(choices=[('EPL', 'etherpadlite'), ('DJP', 'djangopad'), ('HMD', 'hackMD')], default='DJP', max_length=3, verbose_name='backend'),
        ),
    ]
