# Generated by Django 2.0.5 on 2018-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padman', '0003_auto_20180530_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='padcategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
