# Generated by Django 2.0.5 on 2018-05-30 14:42

from django.db import migrations
from django.template.defaultfilters import slugify


def forwards_func(apps, schema_editor):
    PadCategory = apps.get_model("padman", "PadCategory")
    db_alias = schema_editor.connection.alias
    for category in PadCategory.objects.using(db_alias).all():
        category.slug = slugify(category.name)
        category.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('padman', '0004_padcategory_slug'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
