# Generated by Django 2.0.5 on 2018-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padman', '0005_auto_20180530_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='padcategory',
            name='show_non_leaf',
            field=models.BooleanField(default=False),
        ),
    ]
