# Generated by Django 2.0.5 on 2018-05-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padman', '0007_auto_20180530_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padgroup',
            name='group_mapper',
            field=models.SlugField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='padgroup',
            unique_together={('group_mapper', 'server')},
        ),
    ]
