# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0002_remove_padauthor_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padauthor',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='padgroup',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='padserver',
            options={'verbose_name': 'server', 'verbose_name_plural': 'servers'},
        ),
        migrations.AddField(
            model_name='pad',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
