# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0006_auto_20180220_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etherpadlite.PadCategory'),
        ),
        migrations.AlterField(
            model_name='padgroup',
            name='groupID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='padgroup',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='padgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etherpadlite.PadCategory'),
        ),
    ]
