# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0007_auto_20180220_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pad',
            name='template_is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pad',
            name='template_padname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='pad',
            name='template_password',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
