# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0008_auto_20180221_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='padid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
