# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0009_auto_20180221_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
