# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0010_auto_20180221_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='template_slug',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
