# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0011_pad_template_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='padgroup',
            name='group_mapper',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
