# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 15:17
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify
import re


# https://stackoverflow.com/questions/1175208/elegant-python-function-to-convert-camelcase-to-snake-case#1176023
def convert(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

def generate_mapper(apps, schema_editor):
    PadGroup = apps.get_model("etherpadlite", "PadGroup")

    for group in PadGroup.objects.all():
        group.group_mapper = slugify(group.name if group.name else group.group.name).replace("-","_")
        group.save()

def clear_mapper(apps, schema_editor):
    PadGroup = apps.get_model("etherpadlite", "PadGroup")

    for group in PadGroup.objects.all():
        group.group_mapper = None
        group.save()        


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0012_padgroup_group_mapper'),
    ]

    operations = [
        migrations.RunPython(generate_mapper, clear_mapper)
    ]
