# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0013_auto_20180221_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padgroup',
            name='group_mapper',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
